FROM ubuntu:12.04

RUN apt-get clean all && apt-get update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install -y wget git curl iputils-ping net-tools vim cmake gcc g++ gdb libboost-all-dev && \
    apt-get clean && \
    apt-get autoremove &&\
    rm -rf /var/lib/apt/lists/* &&\
    rm -rf /var/cache/apt/archives/*
    
WORKDIR /app
